apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccb
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["kubeflow.org"]
    resources:
      - tfjobs
      - pytorchjobs
      - experiments
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccb
  namespace: ccb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ccb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ccb
subjects:
  - kind: ServiceAccount
    name: ccb
    namespace: ccb