apiVersion: v1
kind: Namespace
metadata:
  name: launcher-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: launcher-test
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["kubeflow.org"]
    resources:
      - tfjobs
      - pytorchjobs
      - experiments
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: launcher-test
  namespace: launcher-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: launcher-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: launcher-test
subjects:
  - kind: ServiceAccount
    name: launcher-test
    namespace: launcher-test