kind: Job
apiVersion: batch/v1
metadata:
  name: test-tfjob-launcher
  namespace: launcher-test
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  template:
    metadata:
      name: test-tfjob-launcher
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: launcher-test
      restartPolicy: Never
      containers:
        - name: test-tfjob-launcher
          image: docker.io/chongchuanbing/kubeflow-launcher-component:v1
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --group
            - "kubeflow.org"
            - --plural
            - "tfjobs"
            - --version
            - "v1"
            - --spec
            - |
              apiVersion: kubeflow.org/v1
              kind: TFJob
              metadata:
                generateName: mnist-player-tfjob-demo-
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                cleanPodPolicy: None
                tfReplicaSpecs:
                  PS:
                    replicas: 1
                    restartPolicy: OnFailure
                    template:
                      metadata:
                        annotations:
                          sidecar.istio.io/inject: "false"
                      spec:
                        affinity:
                          nodeAffinity:
                            requiredDuringSchedulingIgnoredDuringExecution:
                              nodeSelectorTerms:
                                - matchExpressions:
                                    - key: tag
                                      operator: In
                                      values:
                                        - NOGPU
                        containers:
                          - name: tensorflow
                            image: docker.io/chongchuanbing/tf-mnist-player:v1
                            imagePullPolicy: Always
                  Worker:
                    replicas: 1
                    restartPolicy: OnFailure
                    template:
                      metadata:
                        annotations:
                          sidecar.istio.io/inject: "false"
                      spec:
                        podAntiAffinity:
                          preferredDuringSchedulingIgnoredDuringExecution:
                            - weight: 100
                              podAffinityTerm:
                                labelSelector:
                                  matchExpressions:
                                    - key: tf-replica-type
                                      operator: NotIn
                                      values:
                                        - worker
                                topologyKey: kubernetes.io/hostname
                        containers:
                          - name: tensorflow
                            image: docker.io/chongchuanbing/tf-mnist-player:v1
                            imagePullPolicy: Always
                            env:
                              - name: NVIDIA_VISIBLE_DEVICES
                                value: "all"
                            args:
                              - '--sync_replicas=True'
                              - '--train_steps=200'
                            resources:
                              limits:
                                aliyun.com/gpu-mem: 1
